## numpy packages:
1. numerical data
2. computations on numerics

In [7]:
import numpy as np


##  differences between numpyarray and list:
1. less memory
2. fast
3. convenient

In [8]:
#1-dimensional array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a1.ndim

2

In [11]:
a1.shape

(3, 3)

In [12]:
a.shape

(5,)

In [16]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])
print(a2.shape[1])

4
3


In [21]:
a3=np.array([],dtype="int32")


In [22]:
a3=np.append(a3,int(input()))
a3

12


array([12])

In [23]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([12, 23, 34, 45, 56, 67])

In [24]:
a2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# slicing:

In [25]:
print(a3[3])

45


In [29]:
print(a2[1,2])

6


In [30]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [31]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [32]:
print(a2[0,0:2])

[1 2]


In [39]:
print(a2[0::3,:])

[[ 1  2  3]
 [10 11 12]]


### iterate through Array:


In [40]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [41]:
for ele in a2.flat:
    print(ele,end=" ")
    

1 2 3 4 5 6 7 8 9 10 11 12 

In [43]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# indexing with boolean array

In [45]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
result=(arr1%2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [47]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# appending array

In [50]:
arr1= np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [51]:
print(np.hstack((arr1,arr2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [52]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


## function
1. zeros()
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [55]:
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
f= np.full((2,2),"siddu")
print(f)

[['siddu' 'siddu']
 ['siddu' 'siddu']]


In [58]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [60]:
#linspace
l =np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [62]:
#rival()
print(np.array(a.flat))
print(a.ravel())

[1 2 3 4 5]
[1 2 3 4 5]


In [63]:
print(a.min())
print(a.max())

1
5


In [64]:
a

array([1, 2, 3, 4, 5])

In [67]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

15


AxisError: axis 1 is out of bounds for array of dimension 1

In [68]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [69]:
np.mean(a)

3.0

In [70]:
np.median(a)

3.0

In [71]:
np.std(a)

1.4142135623730951

# mathematical operations:+,-,*,/,%


In [72]:
arr1= np.arange(1,11)
arr2= np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


## dot()

In [73]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [74]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# applying user-defined function:


In [79]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [80]:
#1/(1+1)-->x/(x+1)
result=[x/(x+1)for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [81]:
f=np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])