In [2]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

56
0.9463115977926849


In [3]:
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[61 10 47]
[[19 97 88 47]
 [86 23 67 53]
 [78  8 50  8]]
[[[10 93]
  [28 55]
  [99 18]
  [58 12]]

 [[70 52]
  [67 67]
  [23 72]
  [36 37]]

 [[63 13]
  [20 30]
  [49 27]
  [ 8 80]]]


In [4]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.871705718625054
[0.29877931 0.6744133  0.63218112]
[[0.47801361 0.77273162 0.61931516]
 [0.63278795 0.42246965 0.68074964]]


In [9]:
a=random.randint(100,size=(3,2)).ravel()
a

array([23, 66, 63, 82, 98, 84])

In [10]:
random.choice(a)

63

In [11]:
random.choice([1,2,3,4,5],size=(4,4))

array([[3, 1, 4, 3],
       [3, 1, 1, 4],
       [1, 1, 3, 1],
       [1, 3, 4, 2]])

### pandas:
1. data manipulation,analysisand cleaning
2. tabular,unlabelled

### creating a dataframe
1. using 2 dictionaries

In [19]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"first":dict1,"second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [21]:
d1={"name":["siddu","vizay","bhavvu"],"address":["hyd","medak","rayalaseema"]}
df1 = pd.DataFrame(d1)
df1

name      address
0   siddu          hyd
1   vizay        medak
2  bhavvu  rayalaseema

In [25]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([45.4,12.3,13.4,14.5,23.7,34.8,78.9,67.8,89.9,78.0])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"coloumn2":s2,"coloumn3":s3}
df3=pd.DataFrame(data)
df3

column1  coloumn2 coloumn3
0        1      45.4        a
1        2      12.3        b
2        3      13.4        c
3        4      14.5        d
4        5      23.7        e
5        6      34.8        f
6        7      78.9        g
7        8      67.8        h
8        9      89.9        i
9       10      78.0        j

### selecting the data from datadrame:
1. loc
2. iloc

In [29]:
df3["coloumn2"]

0    45.4
1    12.3
2    13.4
3    14.5
4    23.7
5    34.8
6    78.9
7    67.8
8    89.9
9    78.0
Name: coloumn2, dtype: float64

In [30]:
df3[["coloumn2","coloumn3"]]

coloumn2 coloumn3
0      45.4        a
1      12.3        b
2      13.4        c
3      14.5        d
4      23.7        e
5      34.8        f
6      78.9        g
7      67.8        h
8      89.9        i
9      78.0        j

In [32]:
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [35]:
df3.loc[2:5,["column1",'coloumn2']]

column1  coloumn2
2        3      13.4
3        4      14.5
4        5      23.7
5        6      34.8

In [36]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [37]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

# retrieving the info of dataframe

In [38]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1     10 non-null int64
coloumn2    10 non-null float64
coloumn3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [39]:
df3.shape

(10, 3)

In [40]:
df3.columns

Index(['column1', 'coloumn2', 'coloumn3'], dtype='object')

In [41]:
df3.index

RangeIndex(start=0, stop=10, step=1)

## viewing data from dataframe

In [42]:
df3.head()

column1  coloumn2 coloumn3
0        1      45.4        a
1        2      12.3        b
2        3      13.4        c
3        4      14.5        d
4        5      23.7        e